### ISSUE TITLE
Replacing graphics not in the CGAlt folder

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/himatsubushi#10]
There are a handful of graphics that are not stored in the CGAlt folder like the Tips screen and the UI elements, so we've been unable to replace them with PS3 assets so far.  (The Tips screen is the only one that bothers me, really...)  I did some digging, and it looks like the rest of the graphics are stored in sharedassets0.assets.  It's a standard Unity assets archive, so I was able to view the contents using a tool called Unity Assets Explorer:

![image](https://cloud.githubusercontent.com/assets/20390474/19949108/59589dce-a126-11e6-9217-96404919e9c6.png)

It looks like the graphics are the .tex Texture2D files.  UAE can export them in a .dds image format.  Theoretically we should be able to modify the .dds files and package an updated .assets file.  Unfortunately, I'm having some trouble opening the .dds files.  I tried opening them in Paint.NET and Gimp, but neither of them display the images correctly.  It seems like only the alpha channel is being displayed?  There must be some other tool out there that can modify dds files.

![image](https://cloud.githubusercontent.com/assets/20390474/19949318/5c07e75e-a127-11e6-81db-600e26545433.png)

I'm also having trouble loading the dds files back into the .assets file after exporting them.  Even if I try importing the dds immediately after exporting without any modifications, it complains about the dds file size.  No idea what's going on, but maybe there's a better tool than UAE.

This is really not a big deal, but if anyone has any ideas on how to move forward with this I'm open to suggestions.

**Comment by enumag** [comment]
From my research Gimp needs a [plugin](http://registry.gimp.org/node/70) to open dds files. But I assume you already found and tried that?

**Comment by enumag** [comment]
Sorry, just a bad number in commit message.

**Comment by P-Chang** [comment]
I found solution for it.
https://github.com/07th-mod/higurashi-patch-compiler/issues/5

and please, find the way to change aspect ratio after source code issue.
I can't.
