### ISSUE TITLE
Issues using original sprites with patch installed

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/himatsubushi#12]
Someone decided to try playing with the original sprites setting after installing the patch and ran into an issue.  All of the sunset/night/rain sprites and bgs in the CGAlt folder have no equivalent image in the CG folder, so any scene that uses those graphics just displays a blank screen when you have the graphics set to original.

This problem affects all 4 chapters.  Not sure if we intend to support the original sprites option, but if we do I can think of 2 ways to fix this.  Either update the script so it's smart enough to load the right images based on your graphics setting, or add a bunch of images to the CG folder so that every image in CGAlt has a corresponding image in CG with the same name and path.

**Comment by enumag** [comment]
In my opinion it would be best to use the original sprites settings for PS3 sprites and alternative for the new MG sprites.

**Comment by DoctorDiablo** [comment]
That's doable too, but we'd still have the same problem that those sprites don't have sunset/night variants.

**Comment by enumag** [comment]
Yes but maybe someone from the community can make them... If not a while ago I tried to write a script to generate them which we could use. The images it outputs don't look as good as those made in photoshop (the algorithm is very simple) but they're still good enough I think. On the bright side they would be consistent across all new episodes.

**Comment by ItaloKnox** [comment]
> Someone decided to try playing with the original sprites setting after installing the patch and ran into an issue. All of the sunset/night/rain sprites and bgs in the CGAlt folder have no equivalent image in the CG folder, so any scene that uses those graphics just displays a blank screen when you have the graphics set to original.

That's because they're running the voice and graphics patch, people who want to play with the original graphics should stick with the voices only patch.

Edit: I think we already discussed that before. Providing a solution for this sounds like a pain in the ass, unless someone want to go through editing all the graphics to properly support everything. I'll gladly merge these changes if it means we can discontinue the voices-only patch.

**Comment by DoctorDiablo** [comment]
It does seem like a lot of trouble for minimal payoff.  Maybe we should just add a note in the readme that the original sprites option causes issues and is not supported.

**Comment by enumag** [comment]
@DoctorDiablo This is solved now, right?

**Comment by DoctorDiablo** [comment]
Yeah, this is no longer an issue thanks to the new installer.
