### ISSUE TITLE
Blank screen on main menu's background, and the other first bg in prologue

### ISSUE THREAD

**Issue by gagantous** [07th-mod/himatsubushi#13]
![14](https://cloud.githubusercontent.com/assets/24579576/21738413/799dabfc-d4bf-11e6-94bf-2bf347bce923.JPG)

and there is no such "Federica bernkastel" quote in the first place, skipped to the "this is a work of

 fiction bla bla bla"

this line had no bg, 
![15](https://cloud.githubusercontent.com/assets/24579576/21738448/db9fa792-d4bf-11e6-9d3e-dbaefddda2be.JPG)

and this one had no bg and character cg, but voiced patch works perfectly

![5](https://cloud.githubusercontent.com/assets/24579576/21738462/222e3476-d4c0-11e6-8504-6a13193c7b0f.JPG)

thank you, and i apologize if this kind of issues have been asked before by someone ( and sorry for my bad english )

**Comment by gagantous** [comment]
sorry, i think i have fixed the problem, thanks

**Comment by gagantous** [comment]
Hi again, i got this issue again, and i kinda forgot how to make this works again, and it's same problem, no bg

**Comment by gagantous** [comment]
But now the issue is little bit different from my last issue, now i have installed the side story that included in chapter 4 ( there is 2 chapter as i recall )

**Comment by gagantous** [comment]
but still no bg , i have copy the patch etc

**Comment by ItaloKnox** [comment]
I'm pretty sure you're having issues with your ISP so I recommend to not use the installer. You're clearly getting incomplete downloads and this is breaking your game.

**Comment by gagantous** [comment]
@ItaloKnox  so i have to download the cg and and voice patch manually like on wiki ?

okay, thanks (y)!
