### ISSUE TITLE
Future of the mod

### ISSUE THREAD

**Issue by Grelo** [07th-mod/himatsubushi#14]
New chapter is out on 28.4 i hope this mod is not dead and will continue at usual pace :)

**Comment by ItaloKnox** [comment]
Don't worry, I'm already taking my meds and stocking loads of red bull so we can get Meakashi finished as soon as possible.

Of course I'm joking but Meakashi will be a lot of work (as much as Tatari, I guess). So hopefully everyone will stick around again to make it happens smoothly like Himatsu.

**Comment by enumag** [comment]
Damn I didn't even finish Tatari yet. Need to get back to it. Meakashi is my favorite chapter.

**Comment by Grelo** [comment]
Thats good to hear. Looking forward to it !
