### ISSUE TITLE
Duplicate Sprites?

### ISSUE THREAD

**Issue by jwgrlrrajn** [07th-mod/himatsubushi#15]
I'm going through the graphics master, and it would seem chibimion_Def_0.png is the exact same sprite as me_si_de_a1.png, and chibimion_Shinken_0.png is the same as me_si_ma_a1.png.

Is there a reason for that, or is there some really subtle difference that I'm not seeing?

**Comment by ItaloKnox** [comment]
This one is for you, @Grelo.

I'm also interested since if there's anything wrong we need to update it asap.

**Comment by Grelo** [comment]
@jwgrlrrajn Yep, its the same, dunno why, maybe i overlooked it and added it from ps3 again. But if you want to delete something you need to edit it in script too, because im sure in script they are under their respective names even if they are same.

**Comment by enumag** [comment]
I [updated](https://github.com/07th-mod/himatsubushi/commit/69d8fa6aa31186615c975ed89c964d376c05a8cd) the script. We can safely remove the chibimion files now.

**Comment by Grelo** [comment]
@enumag Btw every chapter has lots of duplicates, like 3x the same BG and so on.....Its because when DoctorDiablo was making simple graphic mod and he didnt found ps3 variant he chose the closest so if u have some simple fast method we can delete them.

P.S. Meakashi will not have this issue since im making it from scratch chapter after chapter.

**Comment by enumag** [comment]
@Grelo I don't have a simple way to detect them. Yet. I'll write some script to take care of it. Thanks for bringing it to my attention.

**Comment by enumag** [comment]
Oh boy. The images are the same, yet not the same. They don't have the same file hash and not even the same filesize so it is not easy to detect the duplicates. I'm not sure if this will be faster to do by hand or to write a script. The script would be far more complicated than I expected.

**Comment by enumag** [comment]
Solved. We just need to deploy the new patches.
