### ISSUE TITLE
Making MG-esque sprites for Young!Mion

### ISSUE THREAD

**Issue by jwgrlrrajn** [07th-mod/himatsubushi#16]
So, I tried my hand at making a younger version of Mion for the MG patch, and the first order of business was to shrink her chest to a more age appropriate size. I managed to get a good portion of it done, but I've hit a snag with the sleeve on the left and the stitching on the shirt. My main issues are trying to make the torso outline visibly different from the sleeve stitching, and trying to wrinkle the left sleeve to match the right sleeve. After I can get that done, I can move onto resizing the body itself, and possibly recoloring the shirt. Would anybody be willing to give this part a try though? (NOTE: .psd file is zipped because I can't attach .psd's directly). 
![me_si_aw_a1](https://cloud.githubusercontent.com/assets/13456824/25967346/774528c6-3653-11e7-955a-27ae6bdaf7ba.png)
[me_si_aw_a1.psd.zip](https://github.com/07th-mod/himatsubushi/files/994157/me_si_aw_a1.psd.zip)

**Comment by enumag** [comment]
It is not easy for me to say this critique because I really appriciate your effort. It doesn't feel right to make Mion a complete pettanko. If you look at MG Satoko (11 years) and Rika (10 years) you can already see some minor breast development. Mion is normally 16 so with Himatsubushi being set to 5 years ago she should be around 11 and should not have her chest completely flat - she should have the same size as Satoko or tiny little bit more. Really sorry about this I know it was my idea and I'm grateful you're trying to go with it (I didn't expect it at all). Still personally I would not use a pettanko Mion to play Hima.

**Comment by jwgrlrrajn** [comment]
Hmm, that actually makes things slightly easier as far as the stitching goes. Still need help with the sleeve, but...
![me_si_aw_a1-v2](https://cloud.githubusercontent.com/assets/13456824/25971342/87c3238e-3661-11e7-94ad-bdee79c9a15d.png)
[me_si_aw_a1-v2.zip](https://github.com/07th-mod/himatsubushi/files/994381/me_si_aw_a1-v2.zip)

**Comment by enumag** [comment]
Much better! I really like this Mion. :-)

**Comment by enumag** [comment]
Would it be too much to ask for to make her shirt different color? Just so that she doesn't seem to wear the same clothes for five years.

Perhaps also flipping her horizontally for more difference from her normal sprite? This can be easily done later of course.

**Comment by jwgrlrrajn** [comment]
Not sure about flipping horizontally, since faces don't really seem to look right when flipped, in my experience. However, I was already planning on making her shirt a different color, so that'll be something to look forward to. I'll have to try a few different colors to see which one works best though.

Incidentally, given that Rika's only 5 in this one, I made a slight adjustment to her sprite based on what you told me earlier (resizing to come soon).
![rika](https://cloud.githubusercontent.com/assets/13456824/25972539/01b6978a-3666-11e7-9d1d-40121b676d62.png)

**Comment by enumag** [comment]
You're probably right - flipped Rena for example doesn't look right at all.

Very good work with Rika! She might also use a different clothes color. And perhaps shorter hair?

Looking forward to alernative color for Mion!

**Comment by jwgrlrrajn** [comment]
Leaving the clothes color as is on Rika to match the CG's. I might try shorter hair though. Let me get back with you.

**Comment by jwgrlrrajn** [comment]
Here's some different colors I came up with for Mion's shirt...

![image](https://cloud.githubusercontent.com/assets/13456824/25974044/757d1fee-366c-11e7-8190-2fc9f0527894.png)

EDIT: Also, here's the shorter haired version of Rika with the regular to the left for comparison. ![rika](https://cloud.githubusercontent.com/assets/13456824/25975828/4c648a98-3676-11e7-9db8-eb2d4303ba61.png)

**Comment by enumag** [comment]
Mion looks great. I can't decide between pink and red. Maybe leaning very slightly to pink. It might be nice to hear opinions from more people.

I don't like the end of Rika's shorter hair. The end just seems too... sudden?

I had an idea of my own about applying a [transparent gradient](https://cloud.githubusercontent.com/assets/539462/25983219/87994460-36e3-11e7-9fae-85825e7d08bf.png) to the end of her hair. I know it is unnatural and would normally never suggest it but for mysterious character like Rika it just might work. (My version is of course just a concept made by adding a few rectangles. I'm can't doo this kind of this stuff.) If you don't like it just go with your version.

**Comment by jwgrlrrajn** [comment]
I'm having trouble deciding between pink and red myself. On the one hand, the pink matches the skirt from the PS3 Young!Mion, but red seems to suit her personality more. Maybe I can see what happens if I blend the two colors, but more likely, I'll have to settle this via majority vote.

I'll have to see what I can do with Rika's hair. The gradient doesn't really work. Maybe if it was Hanyuu...

**Comment by enumag** [comment]
@Grelo @ItaloKnox @DoctorDiablo What do you guys think about the red and pink Mion? Which is better?

**Comment by enumag** [comment]
@Maelstrom1 You were also interested in the MG patch so let's here your opinion about young Mion too.

**Comment by ItaloKnox** [comment]
Hm........ I think I'll take red. Both looks nice but I like red, so that's it.

**Comment by Maelstrom1** [comment]
Red and pink are both equally fine. Blue looks oversaturated, though.

**Comment by DoctorDiablo** [comment]
Red and pink both look good.

**Comment by enumag** [comment]
Let's go with red then. As @jwgrlrrajn said it suits her personality better.

**Comment by Grelo** [comment]
Pink is the best( fitting and has most details preserved) but im not using MG sprites so you guys should decide whats best for you and others ;)

**Comment by jwgrlrrajn** [comment]
Finished making the Chibi!Rika sprites with the shorter hair.
![ri_si_de_a1](https://cloud.githubusercontent.com/assets/13456824/26022211/4d352f38-3764-11e7-98e5-1823bcbc6513.png)

And, here's Mion's size comparison (made a very slight color adjustment too).
![mion](https://cloud.githubusercontent.com/assets/13456824/26022353/c1c21970-3768-11e7-8eda-f485cbad457d.png)

**Comment by enumag** [comment]
Both are really cute! :-)

![rena](http://img.desmotivaciones.es/201307/omochikaerii.jpg)

Mion-chan might be a little bit higher - compare her height with MG sprites of Satoko (same age) and Rika (year younger) - both are slightly higher than your Mion and I always thought Mion was the tall type.

Rika-chama on the other hand is just 5 so maybe even smaller than this? Just a bit though, making her as small as she really should be at 5 years would probably be too small for a VN. She just should be visibly smaller than Mion, that's all.

**Comment by jwgrlrrajn** [comment]
About that... The PS3 sprites were inconsistent with this. I made Mion shrink to the same percent difference as the PS3 version had her (slightly taller, actually). However, I noticed that Chibi!Rika didn't shrink at all, and that was apparently because Chiba!Rika's sprite showed a higher percentage of her body. So, as a non specific example, let's say a character's older sprite showed them from the waist up... Well, the young version, for whatever reason, showed them from the knees up. Not really sure about the best way to handle that.

~~EDIT: Actually, I have an idea. BRB...~~
Here we go. Yet another resized Mion, with Satoko and Chibi!Rika for comparison. What I did was I shrunk her the same percentage as Rika, but I moved her down a few pixels to compensate for the remaining height differential between her and Satoko (Note: I ended up moving her up another 4 pixels to make her slightly taller than Satoko, but that was after I made this shot).
![mion comparison](https://cloud.githubusercontent.com/assets/13456824/26022642/19429772-3770-11e7-92fd-cdf27c5b7074.png)

**Comment by enumag** [comment]
Yeah I noticed that as well. Still I think we should use other MG sprites as a reference for height rather than PS3 sprites - MG sprites generally have different proportions but they're consistent. Knowing that normal MG Rika is 10, your Mion looks like 8-9 (except for her chest).

For Rika making her skirt longer is probably difficult so I can't ask you to do the same thing as PS3. However when I put your chibi Mion and chibi Rika side by side the difference in their height is negligible - certainly not enough for 5 year difference.

EDIT: this was written before the previous comment was updated

**Comment by jwgrlrrajn** [comment]
Ah. Here we go. Changed Rika's 90% change to 85%. As for changing Rika's skirt...
![rika short dress](https://cloud.githubusercontent.com/assets/13456824/26022791/a533e94a-3773-11e7-999a-0b861948b9f4.png)

**Comment by enumag** [comment]
Sizes are perfect now! 👍 

I'm not convinced about Rika's alternative skirt - I like her normal skirt better. Considering her bare shoulders this seems way too revealing. It might be nice to have other opinions though?

**Comment by jwgrlrrajn** [comment]
Well, for comparison...
![ri_si_de_a1](https://cloud.githubusercontent.com/assets/13456824/26022859/56dbb276-3775-11e7-8945-b0af5c0d28a9.png)

**Comment by enumag** [comment]
Well as you said the proportions of PS3 sprites are different with her PS3 sprite starting around her knees. instead of higher like MG. Which means her dress on PS3 is way longer than on your MG alternative. In my opinion your last Rika (the one with short skirt) would be perfect with her normal skirt.

**Comment by jwgrlrrajn** [comment]
Made one last alteration for comparison.
![rika short-ish dress](https://cloud.githubusercontent.com/assets/13456824/26022950/a2ce209a-3777-11e7-89e7-9236ca760ac7.png)

**Comment by enumag** [comment]
Both the middle and the right one are great in my opinion! 👍 

I think I should apologize. I'm really really sorry if I was pushing you too much. As you know I'm a perfectionist and all I wrote were basically ideas of what I would have done if I had the capability to do so. I'm really greateful that you endured it and made such awesome looking sprites. Your results are perfect and I'm looking forward to seeing both your Mion and Rika in the game! Thank you!!

**Comment by jwgrlrrajn** [comment]
It's no problem. Your critique of Mion ended up making it easier for me because the small bust size made it to where I didn't need to worry about the stitching or the slightly wrinkled sleeve as much, and your critique of Rika hit a couple of points that work better now that they're fixed.

All that said, I think I'll go ahead and use the middle sprite then, to help differentiate it from the normal Rika sprite (since I don't want to change the color on this one).

**Comment by jwgrlrrajn** [comment]
Now that I have the .zip compiled, I think we can go ahead and close this issue. Thank you all for your feedback. Here's a pic showing the final designs.
![final](https://cloud.githubusercontent.com/assets/13456824/26026169/35a53748-37bc-11e7-915a-75248c6cc389.png)
