### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#21]
@ItaloKnox Somehow [this line](https://github.com/07th-mod/himatsubushi/blob/master/Update/hima_003_03.txt#L831-L832) is not translated at all. Can you translate it please?

**Comment by ItaloKnox** [comment]
Sorry for the wait, I saw this early today but I waited for confirmation since it used some words I'm not really used to.

It should be
``If the doctor didn't have to do anything, then I'm sure it wasn't a big deal.``

The key is that the issue wasn't that big, so the doctor didn't have to do anything. Because of that, it wasn't a big deal. I think you can adapt it to sound a little more natural.

**Comment by enumag** [comment]
Thanks. It actually fits into the dialogue as it is so just some minor adjustments.

```
If the doctor didn't need to do anything, I'm sure it wasn't a big deal.
```

I'm not a native english speaker so I'm not too confident about doing bigger changes.

**Comment by ItaloKnox** [comment]
I just reviewed this one and it seems to be ``It's always for the best when it gets better without the need of medical care``. Could also be ``The best outcome is always when...`` and ``without the doctor's help``. It's up to you to use this translation or keep the previous one. This one is a tad more correct.

**Comment by enumag** [comment]
I wasn't completely satidfied with the original translation anyway. Just... I think I heared the phrase for "it's no big deal" at the end of the voice? Well of course the phrase might have a different meaning in this context... https://www.dropbox.com/s/v18obmm1v4ji46l/100700533.ogg?dl=0

Would this change be good? `It's always for the best when the patient gets better without the need of medical care.`

**Comment by ItaloKnox** [comment]
Yup, looks good! I thought the same at first but looks like it was used in a different meaning, usually it means just that but in some cases it can mean that a choice is better/safer than the other.

**Comment by enumag** [comment]
Fixed, thanks.
