### ISSUE TITLE
Wrong translation?

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#22]
@ItaloKnox This [line](https://github.com/07th-mod/himatsubushi/blob/master/Update/hima_003_04.txt#L2062-L2063) seems off to me. It's certainly true Akasaka was kind of nervous around Rika ever since she warned him at the shrine. But "disgusting" seems inappropriate here. Perhaps just "strange" or something like that? What does the japanese say?

**Comment by ItaloKnox** [comment]
It says ``気味悪く`` (kimiwaraku), which is really disgusting, creepy, uncomfortable, this kind of thing. Maybe changing it to "creepy" will make it sound better.

**Comment by enumag** [comment]
Yep, creepy is good. Thanks!
