### ISSUE TITLE
Another translation issue

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#23]
@ItaloKnox I'd like to improve [this line](https://github.com/07th-mod/himatsubushi/blob/master/Update/hima_004.txt#L1575-L1576) somehow. `It was the day of.`  - day of what? From the context I think it's meant to be `It was the next day.` or something like that. Can you check the japanese for me?

**Comment by enumag** [comment]
Also I found a missing voice a few lines below - https://github.com/07th-mod/himatsubushi/blob/master/Update/hima_004.txt#L1653-L1654. The file was missing in PS3 files but I found it in PS2 voices - https://www.dropbox.com/s/voxdhiq0irxndak/100700770.ogg?dl=0. Can you check that it matches the line? I can't be sure in a case like this.

**Comment by ItaloKnox** [comment]
A literal translation of the japanese would say ``It was that day``. Now, the only that matters is the context. Seems right to change it.

And yes, the voice matches!

**Comment by enumag** [comment]
I'll go with what you wrote. After some reasearch it may have been the next day but didn't have to. Depends on the exact day of GHD in Himatsubushi. Irie died on June 20th and Rika on the day of GHD which generally happens anywhere between 21th and 26th. I was unable to find the exact date for Hima.

Thank you!

**Comment by enumag** [comment]
Damn it. I just found out that at least in this dialogue the voices from PS2 have lower volume than those from PS3. So I need to somehow make the matching voice line louder.

EDIT: Done using Audacity.

**Comment by ItaloKnox** [comment]
I was going to suggest that. I do audio production so if you need me to do it all you have to do is to send the two voices so I can match them.

**Comment by enumag** [comment]
Good to know. I'm satisfied with the result I achieved with Audacity this time but I might ask your help in the future if I run into a similar case. Thanks for the offer.
