### ISSUE TITLE
Omake issues

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#24]
As usual there are some issues int he Omake. I fixed most of them myself though.

At the moment I need some help with [this part](https://github.com/07th-mod/himatsubushi/blob/master/Update/omake_04.txt#L1845-L1854). I tried to find the voices for these lines but it seems that in the PS3 script these two lines are completely different:

```
沙都子rvS20/04/440400266.「……今まで参加できなかった分、盛大に弾け飛んでいますわね」

梨花rvS20/05/440500163.「受験勉強で抑圧されていた人が、大学生になった途端堕落するパターンと同じなのですよ」
```

Can you translate them so that we can put them in instead of the voiceless lines?

**Comment by ItaloKnox** [comment]
This one is hard, I'm really not sure about them. I tried a bit but I'm not satisfied with the results, so I'll check with my friends to see if I can understand it better.

**Comment by ItaloKnox** [comment]
Okay, so I got confirmation and I'm glad I skipped the first one and didn't post it here. It should be:
```
...I'll give my all to make up for not participating until now

This is just like people getting overwhelmed by entrance exams and then becoming degenerates after getting in college.
```
Of course you can adapt it, I think you can get the gist of it.

**Comment by ItaloKnox** [comment]
Oh, by the way, the first sentence can get some cosmetic changes to make it looks like the tensions are high. The character seems to be hyped, so the way I wrote it must look like he (or she?) isn't that much hyped.

**Comment by enumag** [comment]
The first line is Satoko who is a bit hyped. The other character were making fun of her for no screentime in Himatsubushi - Rika in particular. 🤣 

![rika](https://user-images.githubusercontent.com/539462/27006468-cde8b834-4e34-11e7-8561-d5d979e3d4e0.png)

Would something like this be alright?

```
I'll do my best to make up for not participating until now!
I'll do my best to get more screentime from now on! // I assume this is too far from the original though.
```

----

The second line is Rika. The translation you posted seems like something she might say so I think I'll just use it as is.

My thanks to both you and your friends!

**Comment by ItaloKnox** [comment]
Honestly I think it beats the purpose of translating the text to match the voice if you change it to something else. In this case, I would even go with the original text (since that was how it was written) and put the voice lines...

This one seems a little too far from the voice, so I can't say I'm okay with it. But just do what you think it's best.

**Comment by enumag** [comment]
I agree with you. I have no way of knowing how far off my suggestions are which is why I'm posting them here first. You just said both are too different from the original so I'll just use what you posted originally.

**Comment by enumag** [comment]
Ok. I just found out that it's not just these two lines. Apparently there is quite a few lines in the PS3 version that were skipped. Pretty much all of the lines below were skipped. And there might be even more missing in the rest of the omake. I wish we had @Norgus with us, he was good with these things.

```
魅音rvS20/03/440300447.「そ、その声は……圭ちゃん？！？！kvS20/03/440300448.　まさか、圭ちゃんは収録居残り中のはず！」

圭一rvS20/01/440100222.「くっくっくっ……。kvS20/01/440100223.そうさ、今まではそうだった」

圭一rvS20/01/440100224.「収録居残りのたびに、『残りワード数で誰かを抜けば、お疲れさま会に参加してもいいよ』と言われ続けて」

圭一rvS20/01/440100225.「それでも他のキャラと比べても二倍、あるいは三倍以上もある分量をこなすなど不可能、kvS20/01/440100226.というか最初から参加させる気ないだろ音響監督さんよぉぉっ！kvS20/01/440100227.　と思って諦めてきたが……」

圭一rvS20/01/440100228.「ついに俺は抜いた！　あるキャラを！！kvS20/01/440100229.　詩音、これを見やがれぇぇえぇっっ！！」

詩音rvS20/06/440600175.「え？　……げ、げげぇっ？！」

圭一rvS20/01/440100230.「そう！kvS20/01/440100231.　主役として登場パターンが増えた詩音は、当然喋るワード数もこれまでの二倍！kvS20/01/440100232.　しかも魅音とキャストが同じだからさらに二倍！」

圭一rvS20/01/440100233.「その結果！　俺はようやく、ついに居残り免除！！kvS20/01/440100234.　そして詩音っ、今度はお前が居残りだぁあぁぁッッ！！」

詩音rvS20/06/440600176.「うっ、……嘘ぉっ？！kvS20/06/440600177.　私、次の『目明し』でこんなに喋るんですかぁぁあっ？！」

魅音rvS20/03/440300449.「えーっと、……圭ちゃんが約５００で、k|yvS20/03/440300450.詩音は…………２７００越えぇぇっ？！kvS20/03/440300451.　これ、普通のアドベンチャーゲームなら全キャラの総合計数だよっ！！」

梨花rvS20/05/440500161.「……しかも、これに魅ぃの数が加わるのです。kvS20/05/440500162.その数やなんと、」

魅音＆詩音ro75.vS20/06/440600178|S20/03/440300452.「うわぁぁあぁんん、聞きたくない、聞きたくないぃぃっっ！！」

圭一rvS20/01/440100235.「――と、いうわけでだ。kvS20/01/440100236.レナ、感謝するぜぃ！！kvS20/01/440100237.　月にすら見放され真の闇が地上を覆いし時、k|yvS20/01/440100238.漆黒の魔王、前原圭一、降ッ臨ッ！！！！」

沙都子rvS20/04/440400266.「……今まで参加できなかった分、盛大に弾け飛んでいますわね」

梨花rvS20/05/440500163.「受験勉強で抑圧されていた人が、大学生になった途端堕落するパターンと同じなのですよ」
```

@ItaloKnox Anyway while I can search the scripts to see which lines were changed or skipped I can't fix it by myself. Which way do you want to go? Should we try to get it as close to the PS3 as possible or would you rather just leave it as it is? Or maybe @DoctorDiablo could have a look?

**Comment by ItaloKnox** [comment]
I feel like the omake is a big commitment to make when we don't have a real translator. I can help with some stuff, but I'm far from being good enough to do this much. Leaving it to me would drop the quality of the text a lot. I also wish @Norgus was here since he's done quite a lot in those early chapters. Did @DoctorDiablo translate Someutsushi alone? That's quite a feat if true.

I think we should put on hold cases like this where it doesn't influence the story itself. At least until I can help more or we get a translator to work on these issues.

**Comment by enumag** [comment]
Sounds good to me. I'll just leave this issue open, we can return to it later.

As far as I know @DoctorDiablo really did translate Some alone. It's quite impressive.

If we do get a translator later I might be able to write a script to detect differences from the PS3 version for all the chapters. That might of course be a lot of text to translate and would keep the translator busy for quite a while.

**Comment by DoctorDiablo** [comment]
Yeah, it would be great to have an experienced translator to handle issues like this.  I did translate all of Some, but I'm still learning so it's by no means a perfect translation.

I think a lot of the text changes in the PS3 version are a result of censorship though, so in those cases I'd prefer we stick to the original PC script if possible, even if it means some lines are unvoiced.

**Comment by enumag** [comment]
I think we all agree with that. This particular issue goes the other way around with PS3 adding something that was not in the original PC version (or at least is not in the new MG PC version, I don't have the older PC releases).

**Comment by Grelo** [comment]
Not really a problem because PS3 added almost nothing to originals aside from censoring and alts for that, if i remember correctly. The only thing worth adding is Akasakas daughter at the and of Himatsu. But i can be wrong since i worked only from Tatari and maybe forgot something.

Btw how is the progress on ADV ?

**Comment by enumag** [comment]
Found some missing voices in the Omake. Based on the file numbers it should go like [this](https://github.com/07th-mod/himatsubushi/commit/7cb0ae34a7ff4f2c4c0e2c48edac13c7b669c6a1) but I don't think they match the text so I commented them. There are more lines with missing voices after these. I think we can leave this be for now.

**Comment by Norgus** [comment]
I've done some work on the omake now, including the first two lines mentioned here. I'll look at the extra lines tomorrow or Sunday.

**Comment by enumag** [comment]
@Norgus Thanks. Note that there are probably more missing lines that what is mentioned in this issue. Thinking about it the lines mentioned here might not even be the first ones missing. Just drop it if it seems like too much work and not worth it.

**Comment by Norgus** [comment]
I think my last commits add all that's realistically possible to add in. (left the end basically as it is in the PC version because the changes made for Sui don't really make sense here)

**Comment by enumag** [comment]
Thank you @Norgus!
