### ISSUE TITLE
Himatsubushi - can't hear cicadas in the background and the music

### ISSUE THREAD

**Issue by StaphTouchinMeh** [07th-mod/himatsubushi#26]
Hello,

When I open up Himatsubushi, my options on the main menu are obscured by the title and I also can't hear any music when I'm reading.Voices and Sound effects work fine though.

[main menu screen options being obscured by the title](https://i.imgur.com/tEp2WR9.jpg)
[BGM folder](https://i.imgur.com/AInCPe3.png)
[StreamingAssets](https://i.imgur.com/3TCrLDH.png)

Thanks

**Comment by enumag** [comment]
Operating system?

**Comment by StaphTouchinMeh** [comment]
Windows 7 x64-bit

The other chapters work fine but its just Himatsubushi that doesn't play the music and I've looked on the settings and its on

**Comment by P-Chang** [comment]
It seems like you installed himatsubushi mod on meakashi game.

**Comment by ItaloKnox** [comment]
Yep, I also think that's the case. The menu is from Meakashi.

I also checked the installer to be sure if I didn't goof and the installer is pulling the right patch for Hima and Meak, so it's not my fault here.

**Comment by StaphTouchinMeh** [comment]
Alright, thank you.
