### ISSUE TITLE
Miyuki improvements

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#27]
@ItaloKnox Can I ask you to update our Hima patches?

- Add [these](https://www.mediafire.com/file/15o8a7vypfzb2do/HimaNewAudio.rar) to our voice patch. (by @DoctorDiablo)
- And [these](https://mega.nz/#!8IN2CKIK!38EXpJBS7D5p9DLpQmMpq53Yv7YAJKo1LiBWiANzSPE) to our graphics patch. (by @Grelo)

I already updated the scripts with color for Miyuki.

**Comment by ItaloKnox** [comment]
Everything should be updated now, thanks everyone for making it simple. 👍
