### ISSUE TITLE
MoveBustShot

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#28]
@P-Chang You might be able to help me here. There is a scene near the end of Himatsubushi where Akasaka and Miyuki meet Ooishi. In this scene at one point Oishi talks to Miyuki and her sprite blinks to a different position further away from Ooishi as she hides behind Akasaka.

The blink kind of bothers me. I know there is some function called MoveBushShot - the name suggests that it could be used to move an existing sprite with an animation which would be nicer in this case. But I was unable to make it work. Can you do it? If I remember correctly you did have some sprites moving in one of your testing example...

Here is the relevant part: https://github.com/07th-mod/himatsubushi/blob/master/Update/hima_004.txt#L304-L332

**Comment by P-Chang** [comment]
MoveBustshot( layer, textruename, xvector, yvector, zvector, unused, waittime, waitflag );

you need set layer same as value that is used in drawbustshot

zvector have bug, unsed argument was probably priority in BGI Engine.
If wait flag is off, next command start with this.

```
DrawBustshot( 4, "miyuki_Hatena_0", -160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 19, 200, TRUE );
MoveBustshot( 4, NULL, 0, 0, 0, 0, 1000, TRUE );
DialogCommand
```

miyuki_Hatena_0 move to 0 from -160 in 1 seconds. and dialog start after it.

**Comment by enumag** [comment]
@P-Chang That works, thanks! The reason why it didn't work for me was that I had FALSE as the last parameter.
