### ISSUE TITLE
Himatsubushi chapter went missing after side story installed ?

### ISSUE THREAD

**Issue by gagantous** [07th-mod/himatsubushi#29]
I have installed any available side story for chapter 4. After i installed that, where can i read himatshubushi arc ? All i can find is these two side story.

![a](https://user-images.githubusercontent.com/24579576/34468425-7dd3eee8-eebd-11e7-9169-8df4e90b0f50.JPG)

**Comment by enumag** [comment]
That's intentional. The console arcs patch replaces himatsubushi. If you want both himatsubushi and the console arcs installed you will need two copies of the game. The downside is that things like saved files are shared between the two copies because we were unable to solve that.
