### ISSUE TITLE
Missing voice file hima_001.txt

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/himatsubushi#3]
Seems like it doesn't have a voice file.

PlaySE(4, "S05/11/100700110", 128, 64);
    園崎天皇なんて呼ばれるくらいにその発言には影響力があるそうです。
    She has enough clout that you could call her 'Empress Sonozaki'.

**Comment by Kamlingen** [comment]
Found another one. Yukie44001 fit here.

hima_tips_01.txt

OutputLine(NULL, "「…そうですか。",
           NULL, "\"...Oh really?", Line_WaitForInput);
    OutputLine(NULL, "急な出張は大変ですね…。",
           NULL, " It's tough when it's such a sudden assignment...", Line_WaitForInput);

**Comment by ItaloKnox** [comment]
Actually there's no voice file for the first case.

```
S05/11/100700109    「園崎家の頂点は、現頭首の園崎お魎っていう婆さんです。
S05/11/100700111    気をつけて下さいよ、大物です」
S05/11/100700112    「市長だって最敬礼でお迎えするようなＶＩＰですからね。
```

Most likely I goofed and didn't see it (very often you have these gaps between voices, so I probably just filled it without double checking first). I'll leave it there to see if I can find this line in the PS2 voices.

Second case was a nice catch, thanks. Just updated it.

**Comment by Kamlingen** [comment]
@ItaloKnox Found 100700110 in the PS2 files.

**Comment by ItaloKnox** [comment]
Great! Can you do a pull request or upload the file here? I don't have the packs downloaded yet.

**Comment by Kamlingen** [comment]
https://mega.nz/#!1hohRY4J!Q7pmy-mEWF6lox5aarPTa6ybd4SmtPnR7U43NVUSUUc

**Comment by ItaloKnox** [comment]
Many thanks, going to update and release a new version asap. 👍
