### ISSUE TITLE
New voice patch

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#32]
@ItaloKnox You already have PS2 and PS3 voices on the server. Download and unpack PS2 and PS3 spectrum files if you don't have them and [this script](https://www.dropbox.com/s/ojijvjftfq8noyk/himatsubushi-voices.sh?dl=0)

Organize the files like this:

```
himatsubushi-voices.sh
voice/
  ps2/
    00/
    01/
    ...
  ps3/
    s00/
    s01/
    ....
spectrum/
  ps2/
    00/
    01/
    ...
  ps3/
    s00/
    s01/
    ....
```

Now run the script. It will likely take 10+ minutes to finish and won't print anything to output. If it does print anything, post it here.

It will create a himatsubushi directory with the new voice pack. Zip it and uplad to Hanyuu.

**Comment by ItaloKnox** [comment]
Only a handful of errors:
```
cp: cannot stat 'voice/ps3/s05/27/rikaDS22001.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s05/27/rikaDS22001.txt': No such file or directory
cp: cannot stat 'voice/ps3/s05/27/rikaDS22002.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s05/27/rikaDS22002.txt': No such file or directory
```

After you give me the green light I'll upload all the graphics and voices.

**Comment by enumag** [comment]
These errors are bugs caused by the nonlowercase letters in the filenames. We'll need to locate and add them.
