### ISSUE TITLE
ps2 voice file directory structure

### ISSUE THREAD

**Issue by Norgus** [07th-mod/himatsubushi#33]
The current distribution had an inconsistent directory structure.

from hima_001.txt :
```
    ModPlayVoiceLS(4, 0, "ps2/00/104300058", 128, TRUE);
    ModPlayVoiceLS(4, 11, "ps2/10/100700110", 128, TRUE);
```

their locations in the PS2 source structure are
```
HigurashiPS2-Voices\00\104300058.ogg
HigurashiPS2-Voices\10\100700110.ogg
```

in the current distribution they're located at
```
ps2\00\104300058.ogg
ps2\11\100700110.ogg
```

so there's an inconsistency with the second one already (bad reference in the script)
the equivalent PS3 directory structure would be:
```
ps3/s05/00/104300058.ogg
ps3/s05/11/100700110.ogg
```

In onikakushi, watanagashi, and tararigoroshi, we put the ps2 voices in a structure mimicking the PS3 one. Are we going to continue doing that or switch to the structure of the original ps2 game for the ps2 voices? I'll fix the broken reference accordingly once a decision is made.

**Comment by enumag** [comment]
Oni, Wata and Tata are outdated in this regard. Also you should not fix anything regarding this, it's handled automatically. I'll check what's wrong with 100700110.

**Comment by enumag** [comment]
FIxed by https://github.com/07th-mod/higurashi-patch-compiler/commit/1bc913ce59baea2c2c404c780e9545f2df6f636a + https://github.com/07th-mod/himatsubushi/commit/ef83c8f2eb5876e3a069b53138cb41aaef554331 + https://github.com/07th-mod/meakashi/commit/a7989a2201bf77022ee49a8251768e5eaa66df39
