### ISSUE TITLE
Name mismatches

### ISSUE THREAD

**Issue by TellowKrinkle** [07th-mod/himatsubushi#39]
The character 本田屋 is referred to as Hondaya in the Japanese audio, [Motodai](https://github.com/07th-mod/himatsubushi/blob/45134d3d7af82b87069d315d4c1f9012803d903f/Update/hima_001.txt#L3721) by the main script, and [Honda](https://github.com/07th-mod/himatsubushi/blob/45134d3d7af82b87069d315d4c1f9012803d903f/Update/hima_001.txt#L3753) by the colored ADV mode name tag thingies.

Also the character 佐藤 is called Sato in all scenes except two, where he's Satou, [here](https://github.com/07th-mod/himatsubushi/blob/6fb81532c97f2098a5aec4fcb7e91490de927ff4/Update/hima_002_03.txt#L855) and [here](https://github.com/07th-mod/himatsubushi/blob/6fb81532c97f2098a5aec4fcb7e91490de927ff4/Update/hima_002_03.txt#L1018)

**Comment by enumag** [comment]
So which names should we use to unify it? I think somethink close to the voices would be best.

**Comment by enumag** [comment]
ping @DoctorDiablo @Norgus

**Comment by Norgus** [comment]
I would say keep Hondaya and Sato.

**Comment by DoctorDiablo** [comment]
I agree with Norgus.  We should match the audio.

**Comment by orian34** [comment]
Sato is also named Satou in Meakashi.

**Comment by enumag** [comment]
Fixed.
