### ISSUE TITLE
Missing voice file hima_002_03.txt

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/himatsubushi#4]
"「そんないかがわしいところに通った試しなどありません…！」",
           NULL, "\"I would never even try something seedy like that...!\"

101300271?

**Comment by Kamlingen** [comment]
hima_tips_08
Voice line 442600001 goes for both.

OutputLine(NULL, "「別室の越権でしょ。",
           NULL, "\"That's overstepping their boundaries, isn't it?", Line_WaitForInput);
    OutputLine(NULL, "連中、公安に干渉し過ぎですよ。",
           NULL, " They're meddling too much with Public Safety.", Line_WaitForInput);

**Comment by ItaloKnox** [comment]
Yep, first case is right. Thanks for the input, the corrections should be already in the repo. 😄 

Second case seems to be already correct?

```
//「別室の越権でしょ＠連中、公安に干渉し過ぎですよ＠あまり迎合すると悪い先例を残しますね。＠
    PlaySE(4, "S20/00/442600001", 128, 64);
    OutputLine(NULL, "「別室の越権でしょ。",
           NULL, "\"That's overstepping their boundaries, isn't it?", Line_WaitForInput);
    OutputLine(NULL, "連中、公安に干渉し過ぎですよ。",
           NULL, " They're meddling too much with Public Safety.", Line_WaitForInput);
    PlaySE(4, "S20/00/442600002", 128, 64);
    OutputLine(NULL, "あまり迎合すると悪い先例を残しますね。」",
           NULL, " If they keep doing that, they're going to set a bad precedent.\"", Line_WaitForInput);
    OutputLineAll(NULL, "\n", Line_ContinueAfterTyping);
```

**Comment by Kamlingen** [comment]
Ignore the second one :P

**Comment by ItaloKnox** [comment]
Nice, I guess I'll wait for a couple more stuff to fix before pushing _another_ version. Thanks for the reports!
