### ISSUE TITLE
Tips and titles

### ISSUE THREAD

**Issue by orian34** [07th-mod/himatsubushi#41]
![image](https://user-images.githubusercontent.com/12663654/46937473-abf27980-d061-11e8-8682-1fb5b127ab7f.png)
No differentiation for the Mother's diary tips, when there is in the unlock menu
![image](https://user-images.githubusercontent.com/12663654/46937493-bca2ef80-d061-11e8-9ffe-8a654d3d0a63.png)

**Comment by enumag** [comment]
Again already fixed.

**Comment by enumag** [comment]
Actually I'm not sure about this one. This should be handled with those jsons for tips. We have the support in DLL afaik but do we have the actual jsons anywhere? cc @idealpersona
