### ISSUE TITLE
Tips Typo

### ISSUE THREAD

**Issue by orian34** [07th-mod/himatsubushi#42]
![image](https://user-images.githubusercontent.com/12663654/46937585-f542c900-d061-11e8-8ee7-6bf023508ce4.png)
Should be "Chick" instead of "Girl"

**Comment by enumag** [comment]
I'll check again but I believe we fixed this one...

**Comment by enumag** [comment]
Yes it's fixed.

![hima001](https://user-images.githubusercontent.com/539462/46967476-ec2d1880-d0b0-11e8-9b4e-07d91a54d392.png)
