### ISSUE TITLE
New Ending CG

### ISSUE THREAD

**Issue by orian34** [07th-mod/himatsubushi#43]
What about this? We don't have the picture?
I feel like it could be nice to have it. 
The current script only writes it like a normal line. It happens at the very end of Day 4.
Here's the link and the pictures.
https://youtu.be/BQyKROV-KbM?list=PLt1PMnqoYKpQoPFjH-oVpDKhwc7_I7xFp&t=1402
![image](https://user-images.githubusercontent.com/12663654/46937654-2622fe00-d062-11e8-97c8-94fce422aa3b.png)

**Comment by enumag** [comment]
Wasn't this fixed by https://github.com/07th-mod/himatsubushi/commit/04b9b6d59ffae39db57b02e4d05a18e1fccfc125?

**Comment by orian34** [comment]
Seems like I forget my own work sometimes...
