### ISSUE TITLE
Himatsubushi bad end

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/himatsubushi#44]
This ending is extremely short.  I almost wonder if it's worth adding at all.

Here's the script for it: [hima_badend.txt](https://github.com/07th-mod/himatsubushi/files/3490458/hima_badend.txt)  The choice that leads to the bad end happens right [here](https://github.com/07th-mod/himatsubushi/blob/master/Update/hima_003_03.txt#L3780)

![image](https://user-images.githubusercontent.com/20390474/62839688-655ab500-bc5b-11e9-8603-e3bb84959ff2.png)

**Comment by orian34** [comment]
not sure if it's worth, yeah

**Comment by enumag** [comment]
Discussed it with @ItaloKnox and we decided to add it anyway. I'll ask Meera to translate it after Tsumi's bad end.

**Comment by enumag** [comment]
The bad end has been added and released some time ago.
