### ISSUE TITLE
Rendering issues in Rika's niyari sprites

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/himatsubushi#46]
As reported on Discord:

![](https://cdn.discordapp.com/attachments/392489108875771906/676007839998803979/SPOILER_1.jpg)
![](https://cdn.discordapp.com/attachments/392489108875771906/676007844012752896/SPOILER_2.png)
![](https://cdn.discordapp.com/attachments/392489108875771906/676007845098946570/SPOILER_QQ20200208210152.png)

All niyari sprites share the same issues. It's easier to clean them manually than check the Switch files.

**Comment by enumag** [comment]
Closed by https://github.com/07th-mod/himatsubushi/commit/4e53b6d721e3099e91e6c8b14781e267e7321951
