### ISSUE TITLE
Small text overrun in Chapter 2 w/ ADV mode. 

### ISSUE THREAD

**Issue by scramel** [07th-mod/himatsubushi#49]
![screenshoy](https://user-images.githubusercontent.com/61172451/79023519-822eeb80-7b4e-11ea-8370-4f28973bbbda.png)

**Comment by drojf** [comment]
See commit 0a1c568 

> Fix Text Overflow (Fix #49)
> 
>   - Fix by rewording sentence slightly
>   - The sentence is still very wordy/awkward, but I don't want to
>     change it too much since I can't read the original Japanese text
