### ISSUE TITLE
Voice errors

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/himatsubushi#5]
Should be 100700475 not 1007004765.

hima_003_03

PlaySE(4, "S05/11/1007004765", 128, 64);
    OutputLine(NULL, "「まさか。",
           NULL, "\"No way.", Line_WaitForInput);

**Comment by Kamlingen** [comment]
Change the folder address from S14 to S05.

hima_003_05

PlaySE(4, "S14/27/100500198", 128, 64);
    OutputLine(NULL, "……でも、ならばこれは一体、誰の予定なの…？」",
           NULL, " ...But then whose plan would it be...?\"", Line_Normal);

**Comment by Kamlingen** [comment]
Change the folder address from S14 to S05.

hima_003_05

PlaySE(4, "S14/27/100500218", 128, 64);
    OutputLine(NULL, "「……死にたくない。」",
           NULL, "\"...I don't want to die.\"", Line_WaitForInput);

**Comment by Kamlingen** [comment]
100700669 should go here.

hima_004

OutputLine(NULL, "　なっはっはっは！",
           NULL, " Na ha ha ha!", Line_WaitForInput);

**Comment by Kamlingen** [comment]
You have to add 100700766 from the PS2 files.

hima_004

PlaySE(4, "S05/11/100700766", 128, 64);
    OutputLine(NULL, "全裸で裸足。",
           NULL, " That's because while she was completely naked,", Line_WaitForInput);

**Comment by Kamlingen** [comment]
~~Not sure about this one 100700338~~

~~hima_002_03~~

~~OutputLine(NULL, "「今日の私の負け分を、ちょーっぴり返してくれればいいだけじゃないですか。",
           NULL, "\"You can just give back a little of what I lost tonight.", Line_WaitForInput);~~

**Comment by Kamlingen** [comment]
Couldn't find any voice files for these.

**hima_002_03**

OutputLine(NULL, "「あぁ、女の子が体操服にメイドさんな格好で出てくるってお店？",
           NULL, "\"Oh, that place where the girls dress up in gym clothes and maid uniforms?", Line_WaitForInput);

OutputLine(NULL, "　べろべろべろ〜〜！！！",
           NULL, " Slurp slurp slurp~~!!!", Line_WaitForInput);

**hima_004**

OutputLine(NULL, "意図的に臓器を引きずり出して、四方に散らして見せました。」",
           NULL, " Her organs were deliberately removed and scattered about.\"", Line_WaitForInput);

OutputLine(NULL, "「お客様、お客様…。",
           NULL, "\"Sir, sir...", Line_WaitForInput);
    OutputLine(NULL, "本機は着陸態勢に入りました。",
           NULL, " We're preparing to land.", Line_WaitForInput);
    OutputLine(NULL, "申し訳ございませんが、シートベルトをお締めになってください。」",
           NULL, " Excuse me, but will you please fasten your seatbelt?\"", Line_Normal);
    ClearMessage();

**Comment by Kamlingen** [comment]
You have to add 440400271 from the PS2 files.

omake_04

PlaySE(4, "S20/04/440400271", 128, 64);
    OutputLine(NULL, "　あの両手にいっぱいの剣は。",
           NULL, " All those swords in her hands.", Line_WaitForInput);

**Comment by Kamlingen** [comment]
~~440400273 should go here.~~

~~omake_04~~

~~OutputLine(NULL, "　黒…むが…！！！」",
           NULL, " The Blac---hrmph!!!\"", Line_WaitForInput);~~

**Comment by Kamlingen** [comment]
Spelling mistake? (tenatively)

omake_04

OutputLine(NULL, "『目明し編（仮称）』となります。",
           NULL, "We've tenatively called it 'Meakashi'.", Line_WaitForInput);

**Comment by ItaloKnox** [comment]
> Not sure about this one 100700338

This is actually the wrong voice file. There's nothing in the PS3 voices, maybe there's something in PS2.

> Couldn't find any voice files for these.

The two lines of 002_03 and the first of 004 are not present in the PS3 version. Will see if I can find those in PS2 voices.
They completely censored it. Last three lines are meant to be like that, I guess.

> 440400273 should go here.

Actually a completely different voice line, will also check on PS2 voices.
`S20/04/440400273  　それはいくらなんでも反則…むが…！！！」`

All the others were corrected based on your input. Thank you!
