### ISSUE TITLE
hima_003_03 missing text

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/himatsubushi#6]
Seems like the english text is missing.

//「お医者の世話にならずに済むなら、それに越したことはないです＠んっふっふっふ…！￥
    OutputLine(NULL, "「お医者の世話にならずに済むなら、それに越したことはないです。",
           NULL, "", Line_WaitForInput);
    OutputLine(NULL, "んっふっふっふ…！」",
           NULL, " Nfufufu...!\"", Line_Normal);
    ClearMessage();

//「お医者の世話にならずに済むなら、それに越したことはないです＠んっふっふっふ…！￥
    PlaySE(4, "S05/11/100700533", 128, 64);
    OutputLine(NULL, "「お医者の世話にならずに済むなら、それに越したことはないです。",
           NULL, "", Line_WaitForInput);
    OutputLine(NULL, "んっふっふっふ…！」",
           NULL, " Nfufufu...!\"", Line_Normal);
    ClearMessage();

**Comment by ItaloKnox** [comment]
Nice catch, went ahead and contacted a friend who knows a lot of japanese (this one was kinda convoluted for me) and we adapted it together. Would never find this bug by myself, I guess I should also report it to MG.
