### ISSUE TITLE
Replacement for bg_193

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/himatsubushi#8]
Similar issue with blurriness. Here is a replacement for bg_193.

https://mega.nz/#!M1I0hQpS!UxUvznPI-o5409tOLg6155I9mdtivdK_vmUgImmTgLs

**Comment by ItaloKnox** [comment]
I'll hold this and Tatari issue #18 while I'm looking for a more practical way of pushing graphics updates. Both should be in the repos, but not versioned yet.
